[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "the3-ml-collab"
version = "0.0.1"
description = "California Housing price regression (Git/DVC collaboration project)"
authors = [
  { name = "The3" },
]

readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",

]
dependencies = [
    "ipython",
    "jupyterlab",
    "loguru",
    "matplotlib",
    "notebook",
    "numpy",
    "pandas",
    "pip",
    "python-dotenv",
    "pyyaml",
    "joblib",
    "scikit-learn",
    "tqdm",
    "typer",
    "dvc[s3]>=3.67.1",
]
requires-python = "~=3.12.0"

[dependency-groups]
dev = [
    "detect-secrets>=1.5.0",
    "jupytext>=1.19.5",
    "pre-commit>=4.6.2",
    "pytest",
    "ruff",
]

[tool.flit.module]
name = "src"

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.ruff]
line-length = 99
src = ["src"]
include = ["pyproject.toml", "src/**/*.py", "tests/**/*.py"]

[tool.ruff.lint]
extend-select = ["I"]  # Add import sorting

[tool.ruff.lint.isort]
known-first-party = ["src"]
force-sort-within-sections = true
